steps:
  - label: Build
    command:
      - "git config --global user.email ${BUILDKITE_BUILD_CREATOR_EMAIL}"
      - "git config --global user.name '${BUILDKITE_BUILD_CREATOR}'"
      - "ssh-keyscan dvcs.deloittedigital.com.au >> ~/.ssh/known_hosts"
      - "composer install && composer build -- --publish"
    branches: "master"
    agents:
      queue: drupal
      docker: true
      type: awsecs
